name: jam_game
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flame: ^1.11.0
  flame_audio: ^2.1.4
  flame_bloc: ^1.10.6
  flutter:
    sdk: flutter      
  flutter_bloc: ^8.1.2


dev_dependencies:
  flame_lint: ^1.1.2

flutter:
  assets:
    - assets/images/
    - assets/audio/